### ISSUE TITLE
Having issues using the plugin

### ISSUE THREAD

**Issue by fluxxus** [sanity-io/dashboard-widget-document-list#18]
Hey, after following install instructions, this is the error I get:

```
Uncaught error: Cannot read properties of undefined (reading 'layout')
TypeError: Cannot read properties of undefined (reading 'layout')
    at Poi (https://xxx/static/sanity-a8e1b759.js:7916:23561)
    at https://xxx/static/sanity-a8e1b759.js:7916:23787
```
I guess I am missing something obvious, as always!

**Comment by brownbike** [comment]
+1 I'm migrating from V2 and I'm running into this error.
